### ISSUE TITLE
Weird error...

### ISSUE THREAD

**Issue by lookfirst** [GDATASoftwareAG/tftp#23] opened 2022-05-03 01:54 UTC
Hi there, I'm trying out your tftp server because I'm seeing weird issues with dnsmasq-tftp and the logging is really poor. Unfortunately, I'm also seeing a weird error with your server as well.

At first, I thought it might be the hard coded SetWriteDeadline/SetReadDeadline, so I increased those to 30 seconds. But this shows up in the logs immediately. The log below is built from a recent clone of master.

I think what stands out for me, is the 'client sent unexpected opcode' message. I'm not sure what it should be there, but maybe 0 is the wrong value.

This could entirely be my clients messing up. I have a bunch of servers which are acting very strange (hence trying your server over dnsmasq). They are downloading the first ipxe.efi file and then failing to get the next file, but the thing is, not all of my machines are doing this when I run it with dnsmaq. I think your server makes the issue worse though.

Any help is appreciated.

```
{"level":"info","ts":1651542087.789743,"caller":"logging/logging.go:39","msg":"Received request","args":[],"cmd":"serve","Addr":"10.144.33.122:2075"}
{"level":"info","ts":1651542087.7898347,"caller":"logging/logging.go:39","msg":"Parsed request","args":[],"cmd":"serve","Request":"Opcode: 1\nBlocksize: 1468\nTransferSize: 0, Mode: 1\nPath: ipxe.efi\n"}
{"level":"info","ts":1651542087.7898853,"caller":"logging/logging.go:39","msg":"Sending file...","args":[],"cmd":"serve","clientAddr":"10.144.33.122:2075","File":"ipxe.efi"}
{"level":"debug","ts":1651542087.7899106,"caller":"logging/logging.go:35","msg":"Establish fileTransferConnection","args":[],"cmd":"serve"}
{"level":"info","ts":1651542087.7900414,"caller":"logging/logging.go:39","msg":"Open fileTransferConnection","args":[],"cmd":"serve","ListenAddr":"10.144.33.2:43368","ClientAddr":"10.144.33.122:2075"}
{"level":"info","ts":1651542087.7900715,"caller":"logging/logging.go:39","msg":"Trying to send file to client","args":[],"cmd":"serve","File":"ipxe.efi"}
{"level":"debug","ts":1651542087.790096,"caller":"logging/logging.go:35","msg":"Found matching handler","args":[],"cmd":"serve","handler":"*handler.fsHandler"}
{"level":"debug","ts":1651542087.7901874,"caller":"logging/logging.go:35","msg":"Successfully opened file","args":[],"cmd":"serve"}
{"level":"debug","ts":1651542087.7902129,"caller":"logging/logging.go:35","msg":"Sending OACK","args":[],"cmd":"serve","blocksize":1468,"transfersize":994592}
{"level":"debug","ts":1651542087.7903159,"caller":"logging/logging.go:35","msg":"Package sent","args":[],"cmd":"serve","Bytes":28,"read deadline":30}
{"level":"warn","ts":1651542087.79041,"caller":"logging/logging.go:43","msg":"Read timeout","args":[],"cmd":"serve","Try":0,"error":"read udp 10.144.33.2:43368->10.144.33.122:2075: recvfrom: connection refused","stacktrace":"github.com/gdatasoftwareag/tftp/v2/pkg/logging.logger.Warn\n\tgithub.com/gdatasoftwareag/tftp/v2/pkg/logging/logging.go:43\ngithub.com/gdatasoftwareag/tftp/v2/pkg/tftp.(*rrqResponse).sendBufferWithRetransmissionOnTimeout\n\tgithub.com/gdatasoftwareag/tftp/v2/pkg/tftp/rrq_response.go:303\ngithub.com/gdatasoftwareag/tftp/v2/pkg/tftp.(*rrqResponse).sendOACK\n\tgithub.com/gdatasoftwareag/tftp/v2/pkg/tftp/rrq_response.go:210\ngithub.com/gdatasoftwareag/tftp/v2/pkg/tftp.(*rrqResponse).SendFile\n\tgithub.com/gdatasoftwareag/tftp/v2/pkg/tftp/rrq_response.go:78\ngithub.com/gdatasoftwareag/tftp/v2/pkg/tftp.(*server).sendFile\n\tgithub.com/gdatasoftwareag/tftp/v2/pkg/tftp/server.go:199\ngithub.com/gdatasoftwareag/tftp/v2/pkg/tftp.(*server).rrqWorker\n\tgithub.com/gdatasoftwareag/tftp/v2/pkg/tftp/server.go:173"}
{"level":"warn","ts":1651542087.7905571,"caller":"logging/logging.go:43","msg":"client sent unexpected opcode","args":[],"cmd":"serve","Opcode":0,"stacktrace":"github.com/gdatasoftwareag/tftp/v2/pkg/logging.logger.Warn\n\tgithub.com/gdatasoftwareag/tftp/v2/pkg/logging/logging.go:43\ngithub.com/gdatasoftwareag/tftp/v2/pkg/tftp.(*rrqResponse).sendOACK\n\tgithub.com/gdatasoftwareag/tftp/v2/pkg/tftp/rrq_response.go:225\ngithub.com/gdatasoftwareag/tftp/v2/pkg/tftp.(*rrqResponse).SendFile\n\tgithub.com/gdatasoftwareag/tftp/v2/pkg/tftp/rrq_response.go:78\ngithub.com/gdatasoftwareag/tftp/v2/pkg/tftp.(*server).sendFile\n\tgithub.com/gdatasoftwareag/tftp/v2/pkg/tftp/server.go:199\ngithub.com/gdatasoftwareag/tftp/v2/pkg/tftp.(*server).rrqWorker\n\tgithub.com/gdatasoftwareag/tftp/v2/pkg/tftp/server.go:173"}
{"level":"error","ts":1651542087.7906504,"caller":"logging/logging.go:47","msg":"Failed to send file","args":[],"cmd":"serve","clientAddr":"10.144.33.122:2075","file":"ipxe.efi","error":"client sent unexpected opcode","stacktrace":"github.com/gdatasoftwareag/tftp/v2/pkg/logging.logger.Error\n\tgithub.com/gdatasoftwareag/tftp/v2/pkg/logging/logging.go:47\ngithub.com/gdatasoftwareag/tftp/v2/pkg/tftp.(*server).rrqWorker\n\tgithub.com/gdatasoftwareag/tftp/v2/pkg/tftp/server.go:177"}
```

**Comment by cavus700** [comment] 2022-05-03 05:06
Hi thanks for your feedback. We will have a look into the issue.

**Comment by lookfirst** [comment] 2022-05-03 05:20
Thanks! fyi, I just switched to atftpd and that one seems to be working a bit better (or at least doesn't give me errors) and things seem to be recovering a bit. I have a lot (many thousands) of PXE booted machines so all of this is a bit eventually consistent...

**Comment by cavus700** [comment] 2022-05-03 06:28
I've created a PR to make the Read/WriteTimeout configurable in the config and added some debug logs with the sent/received packages but I was not able to reproduce your error with our TFTP Clients. 
The opcode '0', one of your clients is sending is not part of the protocol. As you can see in the [RFC](https://datatracker.ietf.org/doc/html/rfc1350/) section _5. TFTP Packets_ the first valid opcode is '1'.

If you could provide some debug logs we can have another look at it but if you are already using another TFTP server I will close this issue then.

**Comment by rageagainsthepc** [comment] 2022-05-10 08:44
That being said, we've merged https://github.com/GDATASoftwareAG/tftp/pull/24 and if it turns out that this is in fact just a bug and not a non-spec case, we'd be happy to have a look at it.

**Closed** 2022-10-26 09:42 UTC
